all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
all_joints_names:
- MIRROR_VIEW-GREEN
- MIRROR_VIEW-RED
- MIRROR_VIEW-BLUE
- MIRROR_VIEW-AQUA
- SIDE_PROFILE_VIEW-GREEN
- SIDE_PROFILE_VIEW-RED
- SIDE_PROFILE_VIEW-BLUE
- SIDE_PROFILE_VIEW-AQUA
alpha_r: 0.02
apply_prob: 0.5
batch_size: 4
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets/iteration-2/UnaugmentedDataSet_sa-Gait-Analysis-Basler-acA720-520ucAug23/sa-Gait-Analysis-Basler-acA720-520uc_Auto-Labeler67shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
global_scale: 0.8
init_weights: /notebooks/hdrive/Gait-Analysis/DLC-Projects/sa-Gait-Analysis-Basler-acA720-520uc-Auto-Labeler-2022-08-23/dlc-models/iteration-1/sa-Gait-Analysis-Basler-acA720-520ucAug23-trainset67shuffle1/train/snapshot-52500
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-2/UnaugmentedDataSet_sa-Gait-Analysis-Basler-acA720-520ucAug23/Documentation_data-sa-Gait-Analysis-Basler-acA720-520uc_67shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 8
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /notebooks/hdrive/Gait-Analysis/DLC-Projects/sa-Gait-Analysis-Basler-acA720-520uc-Auto-Labeler-2022-08-23
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
